package rpc

// Request is the JSON envelope for Hive's daemon RPC. ID is a string
// generated by the client. This is JSON-RPC-shaped but NOT strictly
// JSON-RPC 2.0 compliant — there is no `jsonrpc` version field and ID
// is constrained to string (the spec allows string | number | null).
// Acceptable because Hive's daemon socket is internal-only.
//
// Params is the per-method parameter type.
type Request[T any] struct {
	ID     string `json:"id"`
	Method string `json:"method"`
	Params T      `json:"params"`
}

// Response is the JSON envelope for Hive's daemon RPC responses.
// Like Request, this is JSON-RPC-shaped but not strictly 2.0 compliant
// (no `jsonrpc` field, string-only ID). Internal-only.
//
// Result is the per-method success payload; Error is set on failure.
// Exactly one of Result / Error is meaningful. Result is a pointer so
// that `omitempty` actually strips it from error responses (a non-pointer
// generic struct would always marshal a zero value).
type Response[T any] struct {
	ID     string    `json:"id"`
	Result *T        `json:"result,omitempty"`
	Error  *RPCError `json:"error,omitempty"`
}

// RPCError is the structured error payload for failed responses.
type RPCError struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Data    any    `json:"data,omitempty"`
}

// Error codes use the JSON-RPC 2.0 numeric ranges for the standard
// errors (parse/invalid-request/method-not-found/invalid-params/internal),
// plus Hive-specific codes in the -32001..-32099 application-error range.
// The envelope itself is not strictly 2.0-compliant — see Request/Response
// docstrings above.
const (
	ErrParseError     = -32700
	ErrInvalidRequest = -32600
	ErrMethodNotFound = -32601
	ErrInvalidParams  = -32602
	ErrInternal       = -32603

	// Hive-specific
	ErrTaskNotFound       = -32001
	ErrRunNotFound        = -32002
	ErrProjectNotFound    = -32003
	ErrConflictDetected   = -32004
	ErrCostCapExceeded    = -32005
	ErrDaemonShuttingDown = -32006
)
